### ISSUE TITLE
non ascii filenames cause errors on Windows

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#113]
Note: Attempted solved by #1296, but that PR needs a new owner with some Windows foo.

from chrysn from the mailing list:

Prepare:

```
$ mkdir schön
$ echo "include &lt;b.scad>;" > schön/relative.scad
$ echo "include <../schön/b.scad>;" > schön/not_that_relative.scad
$ echo "sphere();" > schön/b.scad
```

Fails, printing wrongly formatted paths in the console
`$ openscad schön/relative.scad`
Fails too, printing wrongly formatted paths
`$ openscad schön/not_that_relative.scad`

In the directory:
`$ cd schön`

Fails, printing correctly formatted paths:
`$ openscad relative.scad`

WORKS:
`$ openscad not_that_relative.scad`

Fails, printing only the filename:
`$ openscad -o test.dxf relative.scad`

Fails, printing only the filename:
`$ openscad -o test.dxf not_that_relative.scad`

The whole thing behaves slightly differently depending on the LANG env. variable, e.g. LANG=en_GB.UTF-8 vs. LANG=C

Same problem happens also with customizer data file as reported in #2453.

##

**Comment by ocastelao** [comment]
Not working in Windows 7 64 bits: "Can't open file "C:/Users/�scar/Documents/OpenSCAD/ViE.stl" for export"

**Comment by t-paul** [comment]
@ocastelao Which places did you try? Command line, Open via Menu entry, Open from the scad file, ...?

**Comment by ocastelao** [comment]
I can create and save .scad files, but i can't export to .stl files using the STL buttom of the graphic interface, because the "�" character.

**Comment by t-paul** [comment]
@ocastelao Could you please have a look at the [2015-06-14 snapshots](http://www.openscad.org/downloads.html#snapshots)? Those include the (proposed) fix for the export.

**Comment by ocastelao** [comment]
I have just tried OpenSCAD 2015.06.14 64 bits, and STL export now works well... Thank you!

**Comment by Sastas** [comment]
Still a problem. I tried the last release. Cannot export STL file to "G:/3D nyomtató/Modellek/" If I try export anywhere else to G(or other drives) what contains only ascii, works well.

**Comment by kintel** [comment]
@Sastas Which version are you using?

**Comment by Sastas** [comment]
2015.03. I downloading the latest update now, and Write here the resoult.

**Comment by Sastas** [comment]
2015.03. Wich is wierd, due I just download from the website. And I thought there is the latest update...

**Comment by kintel** [comment]
@Sastas This was fixed after the latest official release. The fix is available by installing the development snapshots (see at the bottom of the downloads page).

**Comment by Sastas** [comment]
Yes, I do a search and found them. Thanks.

**Comment by nophead** [comment]
The test for including non-ascii filenames fails on 2017.01.20 (git 59df0d1). It shows the filename incorrectly in the title bar and the editor is empty. An MSYS2 build of master shows the filename in the title bar and loads it into the editor. It doesn't find the include file though.

```
WARNING: Can't open include file 'størrelse.scad'. 
Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown variable 'radius'. 
```

In addition the test running on MSYS2 shows the filename incorrectly but it seems to perform the test correctly.
```
openscad-nonascii_sfÃ¦re

1063/1084 Testing: openscad-nonascii_sfÃ¦re
1063/1084 Test: openscad-nonascii_sfÃ¦re
Command: "C:/msys64/mingw64/bin/python.exe" "C:/msys64/home/ChrisP/openscad/tests/test_cmdline_tool.py" "--comparator=" "-c" "C:/msys64/mingw64/bin/convert.exe" "-s" "csg" "-t" "openscad-nonascii" "-f" "sfÃ¦re" "C:/msys64/home/ChrisP/openscad/tests/../Release/openscad.exe" "C:/msys64/home/ChrisP/openscad/tests/../testdata/scad/misc/sfÃ¦re.scad" "-o"
Directory: C:/msys64/home/ChrisP/openscad/tests
"openscad-nonascii_sfÃ¦re" start time: Apr 25 17:31 GMT Daylight Time
Output:
----------------------------------------------------------
run_test() cmdline: ['C:/msys64/home/ChrisP/openscad/tests/../Release/openscad.exe', 'C:/msys64/home/ChrisP/openscad/tests/../testdata/scad/misc/sf\xe6re.scad', '-o', 'C:/msys64/home/ChrisP/openscad/tests/openscad-nonascii-output/sf\xe6re-actual.csg']
using font directory: C:/msys64/home/ChrisP/openscad/tests/../Release/testdata
sfære
stderr output: WARNING: Can't open include file 'stÃ¸rrelse.scad'.
WARNING: Ignoring unknown variable 'radius'.

text comparison: 
 expected textfile:  C:/msys64/home/ChrisP/openscad/tests/regression/openscad-nonascii/sfære-expected.csg
 actual textfile:  C:/msys64/home/ChrisP/openscad/tests/openscad-nonascii-output/sfære-actual.csg
--- 

+++ 

@@ -1 +1 @@

-sphere($fn = 0, $fa = 12, $fs = 2, r = 10);
+sphere($fn = 0, $fa = 12, $fs = 2, r = 1);
<end of output>
Test time =   0.15 sec
----------------------------------------------------------
Test Failed.
"openscad-nonascii_sfÃ¦re" end time: Apr 25 17:31 GMT Daylight Time
"openscad-nonascii_sfÃ¦re" time elapsed: 00:00:00
```

**Comment by Nexusnui** [comment]
It still is a problem in the current build. I think it did work at some point(probably the stable version), because I noticed it when opening an older file.
Currently the file opens in the editor, but preview and render fail with the message:
`ERROR: Parser error: file system error: filesystem error: Cannot convert character sequence: Illegal byte sequence`
Here is an example of screenshot of the current state:

![Image](https://github.com/user-attachments/assets/4593c93d-5c8c-429f-8e03-6c8199d5952b)
(I posted this mainly so people find this issue, when searching for the error message)

**Comment by jordanbrown0** [comment]
PR#6136 fixes some, but not all, of these issues.

In particular, it does not fix include<> or use<> with non-ASCII characters.
