### ISSUE TITLE
Documentation fails to warn that surface()  ignores alpha channel on grayscale PNG with alpha, producing unexpected result.

### ISSUE THREAD

**Issue by eric-s-raymond** [openscad/openscad#5982]
![Image](https://github.com/user-attachments/assets/244c9f34-def2-4dd9-9c1a-052ef64cf510)

This 8-bit grayscale PNG file fails to produce a heightmap when loaded with surface() - all that renders is the support slab.

One warning:

WARNING: GeometryEvaluator: Node didn't fit into cache.

I examined the PNG headers with SNG. It looks perfectly ordinary. 663 pixels square. I have successfuly loaded 500x500 PNGs. Is there an undocumented size limit?

Adding invert=true doesn't fix the problem.

Load code:

surface("murphiclogo.png");

Environment: flatpak beta under Ubuntu 24 Linux on Intel 64bit PC.

**Comment by kintel** [comment]
OpenSCAD ignores the alpha channel of imported PNG, leaving the PNG in your example a black image, yielding a flat surface. If you make the background white (and optionally remove alpha), it should give the result you're after.

Note: OpenSCAD is relatively naive when it comes to generating height map geometry, so it might not be particularly fast.

**Comment by eric-s-raymond** [comment]
Reopening and retitling as documentation bug.

This is the second time in a week I've filed a bug that turns out to have been a consequence of the developers not having an outside view of what an OpenSCAD user needs from the documentation. It's a common and understandable error in mindset, but it's still an error.

If your documentation behaves like a gauntlet users have to run toi prove their worthiness, you're doing it wrong. Thus, when I respond to a bug like this on any of my 100+ projects, my reply *always* ends with "Thank you, I've fixed the documentation" and a commit reference. I urge you to adopt the same practice.

**Comment by bitbasher** [comment]
i see that the wiki page already mentions that alpha is ignored .. does this issue remain open until the print version is updated as well?

**Comment by bitbasher** [comment]
in [this wiki page](https://en.wikibooks.org/w/index.php?title=OpenSCAD_User_Manual/Other_Language_Features&stable=0#Images)

the line "the linear luminance for the sRGB color space (Y = 0.2126R + 0.7152G + 0.0722B). The gray scale values are scaled to be in the range 0 to 100. "

confused me .. the RGB values look to be in a 0-1 range as decimal fractions .. not 0-100 as the next line suggests
??

**Comment by kintel** [comment]
Oh, I didn't get as far as reviewing the docs. The RGB values are interpreted in 0-1 range. The resulting grayscale (also 0-1) is then scaled by 100.
